apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: clipdeck
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: clipdeck
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: notification-service
